TRUNCATE TABLE USERS RESTART IDENTITY CASCADE;

TRUNCATE TABLE REQUESTS RESTART IDENTITY CASCADE;

TRUNCATE TABLE ITEMS RESTART IDENTITY CASCADE;

TRUNCATE TABLE BOOKINGS RESTART IDENTITY CASCADE;

TRUNCATE TABLE COMMENTS RESTART IDENTITY CASCADE;